### ISSUE TITLE
Elements are disjointed from where they ought to be.

### ISSUE THREAD

**Issue by Nox13last** [NightmareXIV/Splatoon#63]
Splatoon's graphics do not correspond to the things or coordinates they are attached to. As pictured, the green circles are disjointed from their gathering nodes, and their tethers from myself.
These elements move strangely as I do, and apart from it being a little nauseating, it only gives me a "ball-park estimate" of where things are.
I expect in Raids and Extreme content, this would suck a whole lot.

In this example, the red circle is set to follow my position precisely. I am revolving a gathering point. It appears that the inter-relational position of elements is fine (the Locked-On gathering spot's element doesn't move all that much), but their relation to the world are off somewhere between "vaguely" and "horribly". The error increases proportional to distance.

Splatoon version 2.1.1.0
Dalamud version 7.0.0.7 (I think - this was taken from the dropdown in _/xldev_)

**Comment by Limiana** [comment]
Hello, this is a problem caused by Dynamic resolution game function that was added recently. Please disable it here:
![image](https://user-images.githubusercontent.com/5073202/190628533-39274d6f-8b1b-4b22-8c5a-3bae84fb9b3e.png)

Additionally, your message was edited to remove your in-game name from it.
If you still have the issue after disabling that option and restarting the game, please report about it again

**Comment by Nox13last** [comment]
Immediate improvement!
![image](https://user-images.githubusercontent.com/1292492/190628849-0e26306f-effb-4c93-9f9b-9470f9a8ff13.png)

Thank you!
(I don't personally mind my IGN getting about (and censoring GIFs is too much work), but I respect the policy. Thanks.)
