### ISSUE TITLE
DSR Layout not working

### ISSUE THREAD

**Issue by Zendeya** [NightmareXIV/Splatoon#86]
for DSR Phase 2
earthquake

P3 all

Phase 4 mirage dive circle

phase 5 
Display tethers

this is what i see not showing up thus far

**Comment by Redmoonwow** [comment]
Excuse me for cutting in.
I don't know about phase 5, but other than that, I think it's because the client language is not English.
For example, Phase 2 earthquake only supports English clients.
So to support other language clients, you need to add it yourself.

If it's a Japanese client, it's around ver6.1, so I don't know if it works, but I can provide it.
![image](https://user-images.githubusercontent.com/50778349/224602620-cfccca59-f2f7-420d-a226-0a89e8abb1a3.png)

![image](https://user-images.githubusercontent.com/50778349/224602551-b5d863d4-242d-4c50-9571-8cc44acfaa26.png)

**Comment by Zeltherion** [comment]
Hi, 

i am on EN client. 
Just for context it was all working till 6.35 drops..

**Comment by Limiana** [comment]
It all sounds like there's a phase detection problem. Did you crashed/relogged during phase 2? In this case you'll need to select phase again manually in `/splatoon` menu after logging back in

**Comment by Zeltherion** [comment]
AHHHHHHHHHHHHH DAMN yes i did! OMG u are a savior.. 
I will test it out again tomorrow if it's that i will close this.

**Comment by Zendeya** [comment]
Yes, it's due to phase detection
